version: "3.2"
services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
      --access-logfile -
      --reload
      "api.wsgi:app"
    restart: always
    ports:
      - "8000:8000/tcp"
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./api
        target: /api
    env_file:
      - variables.env
    depends_on:
        - redis
  worker:
    build: .
    command: celery worker -B -l info -A api.tasks:celery
    restart: always
    volumes:
      - type: volume
        source: data
        target: /data
        volume:
          nocopy: true
      - type: bind
        source: ./api
        target: /api
    env_file:
      - variables.env
    depends_on:
      - redis
  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
volumes:
  data:
