version: "3"
services:
  web:
    build: .
    command: >
      gunicorn -b 0.0.0.0:5000
      --access-logfile -
      --reload
      "main:app"
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./data:/data
    env_file:
      - variables.env
    depends_on:
        - redis
  worker:
    build: .
    command: celery worker -B -l info -A main.celery
    volumes:
      - ./data:/data
    env_file:
      - variables.env
    depends_on:
      - redis
  redis:
    image: redis:4.0.11
    ports:
      - "6379:6379"
